version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd 
    ports:
      - "80:80"
      - "8080:8080/udp"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/vols/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis
    ports:
       - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "word_entries:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
